### ISSUE TITLE
Concert tutorial requester can't find priorities

### ISSUE THREAD

**Issue by jihoonl** [robotics-in-concert/rocon_tutorials#16]
```
[INFO] [WallTime: 1386310170.842078] Gateway : pulling in connection [service][/guimul662ec5181a4c451b8e33cb46ad4d4454/list_apps][/app_manager][guimul662ec5181a4c451b8e33cb46ad4d4454]
Exception in thread Thread-4:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 551, in __bootstrap_inner
    self.run()
  File "/opt/ros/hydro/lib/python2.7/dist-packages/rospy/timer.py", line 194, in run
    self._callback(TimerEvent(last_expected, last_real, current_expected, current_real, last_duration))
  File "/home/jihoonl/test/src/rocon_scheduler_requests/src/rocon_scheduler_requests/requester.py", line 181, in _heartbeat
    self.alloc.priority = self.rset.priority
AttributeError: 'SchedulerRequests' object has no attribute 'priority'

```

**Comment by stonier** [comment]
Fixed in https://github.com/robotics-in-concert/rocon_scheduler_requests/commit/f37da1aeadf5d094e8cca9ab523c92b5cb51782d
