### ISSUE TITLE
Concert tutorial is not running in slow computer

### ISSUE THREAD

**Issue by hughie** [robotics-in-concert/rocon_tutorials#22]
1.  ROS exception is occured : timed out waiting for service [/concert/interactions/set_roles_and_apps]

```
process[concert/hub-7]: started with pid [21673]
process[concert/gateway-8]: started with pid [21738]
Traceback (most recent call last):
  File "/home/huey/rocon/src/rocon_concert/concert_service_manager/scripts/service_manager", line 19, in <module>
    sm = ServiceManager()
  File "/home/huey/rocon/src/rocon_concert/concert_service_manager/src/concert_service_manager/service_manager.py", line 34, in __init__
    self._role_app_loader = rocon_interactions.RoleAppLoader()
  File "/home/huey/rocon/src/rocon_concert/rocon_interactions/src/rocon_interactions/role_app_loader.py", line 111, in __init__
    raise rospy.exceptions.ROSException("timed out waiting for service [%s]" % self._set_roles_and_apps_proxy.resolved_name)
rospy.exceptions.ROSException: timed out waiting for service [/concert/interactions/set_roles_and_apps]
Unhandled exception in thread started by 
sys.excepthook is missing
lost sys.stderr
[concert/services-3] process has died [pid 21402, exit code 1, cmd /home/huey/rocon/src/rocon_concert/concert_service_manager/scripts/service_manager __name:=services __log:=/home/huey/.ros/log/643db8a8-8e48-11e3-bfab-080027c3c5a4/concert-services-3.log].
log file: /home/huey/.ros/log/643db8a8-8e48-11e3-bfab-080027c3c5a4/concert-services-3*.log
process[concert/zeroconf/zeroconf-9]: started with pid [21878]
[INFO] [WallTime: 1391592756.103775] Hub : reset hub variables on the redis server.
[INFO] [WallTime: 1391592756.264296] Hub : advertising 'Concert Tutorial' on zeroconf [_ros-multimaster-hub._tcp, port 6380]
[ INFO] [1391592756.616765880]: Zeroconf: service successfully established [Concert Tutorial][_concert-master._tcp][11311]
[INFO] [WallTime: 1391592756.807019] Gateway : generated unique hash name [Concert Tutorial4d55196252ba4a329cd13bbeb9dd6b37]
Established under name 'Concert Tutorial'
```
1. clients could not join. at this time, only dude and guimul are joined.

I tested on virtual box((using 4CPU, 2GB) in window machine(Core I7, 8GB)

**Comment by stonier** [comment]
Demo for me tomorrow.

Did you try setting a different timeout? The length of that timeout is probably not important and can be almost ridiculously long.

**Comment by hughie** [comment]
I changed time limit to 10 second. ROS exception problem is solved.
But, still client is not connected.

```
[INFO] [WallTime: 1391649756.158334] Scheduler : compatibility tree is valid, attempting to allocate [83206b04-d0bf-44c6-a593-12e0d8d56c53]
[INFO] [WallTime: 1391649758.879321] Scheduler :   allocated [dudette]
[INFO] [WallTime: 1391649760.337285] Gateway : received a flip request [dudette64869545ee8549eab5cd644a6b0c3050][publisher][/conversation/chatter][/dudette/talker]
[INFO] [WallTime: 1391649761.594002] Scheduler :   allocated [dude]
Compatibility Tree
  rocon:/pc/kobuki#turtle_concert/turtle_stroll : []
  rocon:/pc/turtlesim#turtle_concert/turtle_stroll_sim : []
  Pruning...
    rocon:/pc/kobuki#turtle_concert/turtle_stroll : []
    rocon:/pc/turtlesim#turtle_concert/turtle_stroll_sim : []
    Pruning Resolvable Branches
      rocon:/pc/kobuki#turtle_concert/turtle_stroll : []
      rocon:/pc/turtlesim#turtle_concert/turtle_stroll_sim : []
      --> pruned leaves: 
      --> pruned resolvable branches: turtle_concert/turtle_stroll
  Pruning...
    rocon:/pc/turtlesim#turtle_concert/turtle_stroll_sim : []
    Pruning Resolvable Branches
      rocon:/pc/turtlesim#turtle_concert/turtle_stroll_sim : []
  Pruned Tree
    rocon:/pc/kobuki#turtle_concert/turtle_stroll : []
    rocon:/pc/turtlesim#turtle_concert/turtle_stroll_sim : []
[INFO] [WallTime: 1391649761.774361] Scheduler : insufficient resources to satisfy request [4a88170e-3b09-4794-bef8-a89554105d5c]
[INFO] [WallTime: 1391649763.027281] Gateway : received a flip request [dudea95bcefa23e44440aa68e9ea3a7f989a][subscriber][/conversation/chatter][/dude/listener]
[INFO] [WallTime: 1391649765.632177] Requester : state change [pending->alive]
```

**Comment by stonier** [comment]
Let's be safe and set 15 seconds. Can you make a pull request?

**Comment by stonier** [comment]
Can you check the client app managers and see if the app managers are providing any error information?

Is the conductor actually detecting them?

**Comment by hughie** [comment]
Client app managers are just initialized. There are no error message. It shows failure messages as below

```
[WARN] [WallTime: 1391652633.301936] Gateway : failed to register gateway with the hub [16][couldn't resolve hub name on the redis server [192.168.10.129:6380]]
...
[INFO] [WallTime: 1391652658.778876] App Manager : disabling apps requiring capabilities [timed out looking for the capability server]
```

This is full log of client.

```
... logging to /home/huey/.ros/log/cef7fd76-8ed3-11e3-9ccc-080027c3c5a4/roslaunch-huey-VBox-2117.log
Checking log directory for disk usage. This may take awhile.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.
started roslaunch server http://huey-VBox:59061/

SUMMARY
========

PARAMETERS
 * /app_manager/app_store_url
 * /app_manager/auto_start_rapp
 * /app_manager/local_remote_controllers_only
 * /app_manager/rapp_package_blacklist
 * /app_manager/rapp_package_whitelist
 * /app_manager/remote_controller_blacklist
 * /app_manager/remote_controller_whitelist
 * /app_manager/robot_icon
 * /app_manager/robot_name
 * /app_manager/robot_type
 * /app_manager/screen
 * /gateway/default_advertisements
 * /gateway/default_blacklist
 * /gateway/default_flips
 * /gateway/disable_uuids
 * /gateway/firewall
 * /gateway/hub_uri
 * /gateway/hub_whitelist
 * /gateway/name
 * /gateway/network_interface
 * /gateway/watch_loop_period
 * /rocon/screen
 * /rosdistro
 * /rosversion

NODES
  /zeroconf/
    zeroconf (zeroconf_avahi/zeroconf)
  /
    app_manager (rocon_app_manager/rapp_manager.py)
    gateway (rocon_gateway/gateway.py)

auto-starting new master
process[master]: started with pid [2229]
ROS_MASTER_URI=http://huey-VBox:11313/
setting /run_id to cef7fd76-8ed3-11e3-9ccc-080027c3c5a4
process[rosout-1]: started with pid [2308]
started core service [/rosout]
process[zeroconf/zeroconf-2]: started with pid [2359]
process[gateway-3]: started with pid [2436]
process[app_manager-4]: started with pid [2505]
[INFO] [WallTime: 1391652632.298118] Gateway : generated unique hash name [dudea5cd3cc3066d43339b680a73f8415a66]
[INFO] [WallTime: 1391652632.309059] Gateway : adding rule to public watchlist [publisher][.*app_list][.*app_manager]
[INFO] [WallTime: 1391652632.315503] Gateway : adding rule to public watchlist [service][.*platform_info][.*app_manager]
[INFO] [WallTime: 1391652632.317178] Gateway : adding rule to public watchlist [service][.*invite][.*app_manager]
[INFO] [WallTime: 1391652632.318663] Gateway : adding rule to public watchlist [service][.*list_apps][.*app_manager]
[INFO] [WallTime: 1391652632.320410] Gateway : adding rule to public watchlist [service][.*status][.*app_manager]
[INFO] [WallTime: 1391652632.650615] Gateway : checking if zeroconf services are available...
[ INFO] [1391652632.733763464]: Zeroconf: added a listener [_ros-multimaster-hub._tcp]
[ INFO] [1391652632.739703986]: Zeroconf: discovered new service [Demo Concert][_ros-multimaster-hub._tcp][local][2][ipv4]
[ INFO] [1391652632.744798175]: Zeroconf: discovered new service [Concert Tutorial #2][_ros-multimaster-hub._tcp][local][2][ipv4]
[ INFO] [1391652633.245696486]: Zeroconf: resolved service [Demo Concert][_ros-multimaster-hub._tcp][local][2][ipv4][192.168.10.129:6380]
[INFO] [WallTime: 1391652633.276037] Gateway : discovered hub via zeroconf [192.168.10.129:6380]
[WARN] [WallTime: 1391652633.301936] Gateway : failed to register gateway with the hub [16][couldn't resolve hub name on the redis server [192.168.10.129:6380]]
[ INFO] [1391652633.746660973]: Zeroconf: resolved service [Concert Tutorial #2][_ros-multimaster-hub._tcp][local][2][ipv4][192.168.10.128:6380]
[INFO] [WallTime: 1391652633.808714] Gateway : discovered hub via zeroconf [192.168.10.128:6380]
[INFO] [WallTime: 1391652633.952758] Gateway : registering on the hub [Concert Tutorial]
[INFO] [WallTime: 1391652635.629128] Gateway : discovered hub directly [http://localhost:6380]
[INFO] [WallTime: 1391652635.676581] Gateway : registering on the hub [Concert Tutorial]
[ INFO] [1391652636.402510026]: Zeroconf: discovered new service [Concert Tutorial][_ros-multimaster-hub._tcp][local][2][ipv4]
[ INFO] [1391652636.905309584]: Zeroconf: resolved service [Concert Tutorial][_ros-multimaster-hub._tcp][local][2][ipv4][192.168.10.160:6380]
[INFO] [WallTime: 1391652637.221921] Gateway : discovered hub via zeroconf [localhost:6380]
[INFO] [WallTime: 1391652644.210598] App Manager : loading rapp 'rocon_apps/chirp'
[INFO] [WallTime: 1391652649.998013] App Manager : loading rapp 'rocon_apps/talker'
[INFO] [WallTime: 1391652653.530777] App Manager : loading rapp 'rocon_apps/listener'
[INFO] [WallTime: 1391652658.778876] App Manager : disabling apps requiring capabilities [timed out looking for the capability server]
[INFO] [WallTime: 1391652659.117365] App : 'rocon_apps/listener' added to the list of runnable apps.
[INFO] [WallTime: 1391652659.120148] App : 'rocon_apps/chirp' added to the list of runnable apps.
[INFO] [WallTime: 1391652659.123943] App : 'rocon_apps/talker' added to the list of runnable apps.
[INFO] [WallTime: 1391652659.395327] App Manager : initialised.
[INFO] [WallTime: 1391652660.823069] Gateway : adding connection to public interface [publisher][/dudea5cd3cc3066d43339b680a73f8415a66/incompatible_app_list][/app_manager]
[INFO] [WallTime: 1391652660.853344] Gateway : adding connection to public interface [publisher][/dudea5cd3cc3066d43339b680a73f8415a66/app_list][/app_manager]
[INFO] [WallTime: 1391652660.867294] Gateway : adding connection to public interface [service][/dudea5cd3cc3066d43339b680a73f8415a66/status][/app_manager]
[INFO] [WallTime: 1391652660.883692] Gateway : adding connection to public interface [service][/dudea5cd3cc3066d43339b680a73f8415a66/invite][/app_manager]
[INFO] [WallTime: 1391652660.895428] Gateway : adding connection to public interface [service][/dudea5cd3cc3066d43339b680a73f8415a66/list_apps][/app_manager]
[INFO] [WallTime: 1391652660.909425] Gateway : adding connection to public interface [service][/dudea5cd3cc3066d43339b680a73f8415a66/platform_info][/app_manager]
```

Conductor said failed to establish client in concert  In concert:11311 terminal.

```
[INFO] [WallTime: 1391652673.440700] Gateway : removed pull rule [kobuki724c0161fe06431da242ba8c0d0ad879:/kobuki724c0161fe06431da242ba8c0d0ad879/platform_info]
[INFO] [WallTime: 1391652673.445338] Gateway : removed pull rule [kobuki724c0161fe06431da242ba8c0d0ad879:/kobuki724c0161fe06431da242ba8c0d0ad879/list_apps]
[INFO] [WallTime: 1391652673.447633] Gateway : removed pull rule [kobuki724c0161fe06431da242ba8c0d0ad879:/kobuki724c0161fe06431da242ba8c0d0ad879/status]
[INFO] [WallTime: 1391652673.448697] Gateway : removed pull rule [kobuki724c0161fe06431da242ba8c0d0ad879:/kobuki724c0161fe06431da242ba8c0d0ad879/invite]
[INFO] [WallTime: 1391652673.455041] Conductor : failed to establish client [kobuki724c0161fe06431da242ba8c0d0ad879][timed out on remote concert client services]
[INFO] [WallTime: 1391652673.668840] Gateway : abandoning pulled connection [service][/kobuki724c0161fe06431da242ba8c0d0ad879/status][/app_manager][kobuki724c0161fe06431da242ba8c0d0ad879]
[INFO] [WallTime: 1391652673.679702] Gateway : abandoning pulled connection [service][/kobuki724c0161fe06431da242ba8c0d0ad879/platform_info][/app_manager][kobuki724c0161fe06431da242ba8c0d0ad879]
[INFO] [WallTime: 1391652673.689764] Gateway : abandoning pulled connection [service][/kobuki724c0161fe06431da242ba8c0d0ad879/invite][/app_manager][kobuki724c0161fe06431da242ba8c0d0ad879]
[INFO] [WallTime: 1391652673.701496] Gateway : abandoning pulled connection [service][/kobuki724c0161fe06431da242ba8c0d0ad879/list_apps][/app_manager][kobuki724c0161fe06431da242ba8c0d0ad879]
```

Conductor graph could not show client information.
gateway graph client shows redundant clients. But The probelm is from It is running same concert in same network.

**Comment by hughie** [comment]
concert_client info, gateway info, remote gateway info

```
huey@huey-VBox:~$ rostopic echo /concert/conductor/concert_client
WARNING: topic [/concert/conductor/concert_client] does not appear to be published yet
```

```
huey@huey-VBox:~$ gateway_info 
Gateway
  Namespace   : /concert/gateway
  Gateway   : name: Concert Tutorial6bacce93ac1c41729c8717684906ff77
connected: True
ip: huey-vbox
hub_names: ['Concert Tutorial']
hub_uris: ['localhost:6380']
firewall: False
public_watchlist: []
public_interface: []
flipped_connections: []
flip_watchlist: []
flipped_in_connections: 
  - 
    gateway: guimul70210bbfc427410296ca5d12df420c4f
    rule: 
      type: service
      name: /guimul70210bbfc427410296ca5d12df420c4f/stop_app
      node: /app_manager
  - 
    gateway: guimul70210bbfc427410296ca5d12df420c4f
    rule: 
      type: service
      name: /guimul70210bbfc427410296ca5d12df420c4f/start_app
      node: /app_manager
pull_watchlist: 
  - 
    gateway: guimul70210bbfc427410296ca5d12df420c4f
    rule: 
      type: service
      name: /guimul70210bbfc427410296ca5d12df420c4f/platform_info
      node: None
  - 
    gateway: guimul70210bbfc427410296ca5d12df420c4f
    rule: 
      type: service
      name: /guimul70210bbfc427410296ca5d12df420c4f/list_apps
      node: None
  - 
    gateway: guimul70210bbfc427410296ca5d12df420c4f
    rule: 
      type: service
      name: /guimul70210bbfc427410296ca5d12df420c4f/status
      node: None
  - 
    gateway: guimul70210bbfc427410296ca5d12df420c4f
    rule: 
      type: service
      name: /guimul70210bbfc427410296ca5d12df420c4f/invite
      node: None
pulled_connections: 
  - 
    gateway: guimul70210bbfc427410296ca5d12df420c4f
    rule: 
      type: service
      name: /guimul70210bbfc427410296ca5d12df420c4f/list_apps
      node: /app_manager
  - 
    gateway: guimul70210bbfc427410296ca5d12df420c4f
    rule: 
      type: service
      name: /guimul70210bbfc427410296ca5d12df420c4f/invite
      node: /app_manager
  - 
    gateway: guimul70210bbfc427410296ca5d12df420c4f
    rule: 
      type: service
      name: /guimul70210bbfc427410296ca5d12df420c4f/platform_info
      node: /app_manager
  - 
    gateway: guimul70210bbfc427410296ca5d12df420c4f
    rule: 
      type: service
      name: /guimul70210bbfc427410296ca5d12df420c4f/status
      node: /app_manager
  Name        : Concert Tutorial
  Hash Name   : Concert Tutorial6bacce93ac1c41729c8717684906ff77
  Namespace   : /concert/gateway
  Ip/Hostname : huey-vbox
  Connected   : True
  Hubs        : Concert Tutorial [localhost:6380]
  Firewall    : False
  Public Watchlist
       : -
  Public Interface
       : -
  Flip Watchlist
       : -
  Flipped Connections
       : -
  Flipped in Connections
       : guimul70210bbfc427410296ca5d12df420c4f-/guimul70210bbfc427410296ca5d12df420c4f/stop_app-service-/app_manager
       : guimul70210bbfc427410296ca5d12df420c4f-/guimul70210bbfc427410296ca5d12df420c4f/start_app-service-/app_manager
  Pull Watchlist
       : guimul70210bbfc427410296ca5d12df420c4f-/guimul70210bbfc427410296ca5d12df420c4f/platform_info-service-.*
       : guimul70210bbfc427410296ca5d12df420c4f-/guimul70210bbfc427410296ca5d12df420c4f/list_apps-service-.*
       : guimul70210bbfc427410296ca5d12df420c4f-/guimul70210bbfc427410296ca5d12df420c4f/status-service-.*
       : guimul70210bbfc427410296ca5d12df420c4f-/guimul70210bbfc427410296ca5d12df420c4f/invite-service-.*
  Pulled Connections
       : guimul70210bbfc427410296ca5d12df420c4f-/guimul70210bbfc427410296ca5d12df420c4f/list_apps-service-/app_manager
       : guimul70210bbfc427410296ca5d12df420c4f-/guimul70210bbfc427410296ca5d12df420c4f/invite-service-/app_manager
       : guimul70210bbfc427410296ca5d12df420c4f-/guimul70210bbfc427410296ca5d12df420c4f/platform_info-service-/app_manager
       : guimul70210bbfc427410296ca5d12df420c4f-/guimul70210bbfc427410296ca5d12df420c4f/status-service-/app_manager
```

```
huey@huey-VBox:~$ remote_gateway_info 
Local Gateway
  Namespace: /concert/gateway
  Ip/Hostname: huey-vbox
Remote Gateway
  Name        : kobuki
  Hash Name   : kobukie2ef76823630466f877f3fed29f23f5c
  Ip/Hostname : huey-vbox
  Firewall    : true
  Alive       : True
  Connection  : wired
  Latency from Hub(ms)
    Min/Max        : 0.068-0.138
    Average        : 0.103
    Mean Deviation : 0.026
  Public Interface
          : /kobukie2ef76823630466f877f3fed29f23f5c/app_list-publisher-/app_manager
          : /kobukie2ef76823630466f877f3fed29f23f5c/platform_info-service-/app_manager
          : /kobukie2ef76823630466f877f3fed29f23f5c/list_apps-service-/app_manager
          : /kobukie2ef76823630466f877f3fed29f23f5c/invite-service-/app_manager
          : /kobukie2ef76823630466f877f3fed29f23f5c/status-service-/app_manager
          : /kobukie2ef76823630466f877f3fed29f23f5c/incompatible_app_list-publisher-/app_manager
  Flipped Interface
          : -
  Pulled Interface
          : -
Remote Gateway
  Name        : turtlesim
  Hash Name   : turtlesim2c58551dff6943a1bab7800fd94d2d4a
  Ip/Hostname : huey-vbox
  Firewall    : true
  Alive       : True
  Connection  : wired
  Latency from Hub(ms)
    Min/Max        : 0.073-0.197
    Average        : 0.105
    Mean Deviation : 0.037
  Public Interface
          : /turtlesim2c58551dff6943a1bab7800fd94d2d4a/platform_info-service-/app_manager
          : /turtlesim2c58551dff6943a1bab7800fd94d2d4a/incompatible_app_list-publisher-/app_manager
          : /turtlesim2c58551dff6943a1bab7800fd94d2d4a/list_apps-service-/app_manager
          : /turtlesim2c58551dff6943a1bab7800fd94d2d4a/app_list-publisher-/app_manager
          : /turtlesim2c58551dff6943a1bab7800fd94d2d4a/invite-service-/app_manager
          : /turtlesim2c58551dff6943a1bab7800fd94d2d4a/status-service-/app_manager
  Flipped Interface
          : -
  Pulled Interface
          : -
Remote Gateway
  Name        : dudette
  Hash Name   : dudetteafd7b90f02ca49449e7c7b4f22ac390b
  Ip/Hostname : huey-vbox
  Firewall    : true
  Alive       : True
  Connection  : wired
  Latency from Hub(ms)
    Min/Max        : 0.068-0.116
    Average        : 0.080
    Mean Deviation : 0.014
  Public Interface
          : /dudetteafd7b90f02ca49449e7c7b4f22ac390b/status-service-/app_manager
          : /dudetteafd7b90f02ca49449e7c7b4f22ac390b/invite-service-/app_manager
          : /dudetteafd7b90f02ca49449e7c7b4f22ac390b/platform_info-service-/app_manager
          : /dudetteafd7b90f02ca49449e7c7b4f22ac390b/incompatible_app_list-publisher-/app_manager
          : /dudetteafd7b90f02ca49449e7c7b4f22ac390b/app_list-publisher-/app_manager
          : /dudetteafd7b90f02ca49449e7c7b4f22ac390b/list_apps-service-/app_manager
  Flipped Interface
          : -
  Pulled Interface
          : -
Remote Gateway
  Name        : dude
  Hash Name   : dudeed0a0e1b604e412f943eab91ebe7a8d4
  Ip/Hostname : huey-vbox
  Firewall    : true
  Alive       : True
  Connection  : wired
  Latency from Hub(ms)
    Min/Max        : 0.068-0.122
    Average        : 0.091
    Mean Deviation : 0.021
  Public Interface
          : /dudeed0a0e1b604e412f943eab91ebe7a8d4/list_apps-service-/app_manager
          : /dudeed0a0e1b604e412f943eab91ebe7a8d4/incompatible_app_list-publisher-/app_manager
          : /dudeed0a0e1b604e412f943eab91ebe7a8d4/status-service-/app_manager
          : /dudeed0a0e1b604e412f943eab91ebe7a8d4/invite-service-/app_manager
          : /dudeed0a0e1b604e412f943eab91ebe7a8d4/platform_info-service-/app_manager
          : /dudeed0a0e1b604e412f943eab91ebe7a8d4/app_list-publisher-/app_manager
  Flipped Interface
          : -
  Pulled Interface
          : -
Remote Gateway
  Name        : guimul
  Hash Name   : guimul70210bbfc427410296ca5d12df420c4f
  Ip/Hostname : huey-vbox
  Firewall    : true
  Alive       : True
  Connection  : wired
  Latency from Hub(ms)
    Min/Max        : 0.070-0.659
    Average        : 0.207
    Mean Deviation : 0.181
  Public Interface
          : /guimul70210bbfc427410296ca5d12df420c4f/list_apps-service-/app_manager
          : /guimul70210bbfc427410296ca5d12df420c4f/invite-service-/app_manager
          : /guimul70210bbfc427410296ca5d12df420c4f/platform_info-service-/app_manager
          : /guimul70210bbfc427410296ca5d12df420c4f/app_list-publisher-/app_manager
          : /guimul70210bbfc427410296ca5d12df420c4f/incompatible_app_list-publisher-/app_manager
          : /guimul70210bbfc427410296ca5d12df420c4f/status-service-/app_manager
  Flipped Interface
          : Concert Tutorial6bacce93ac1c41729c8717684906ff77-/guimul70210bbfc427410296ca5d12df420c4f/stop_app-service-/app_manager
          : Concert Tutorial6bacce93ac1c41729c8717684906ff77-/guimul70210bbfc427410296ca5d12df420c4f/start_app-service-/app_manager
  Pulled Interface
          : -
Remote Gateway
  Name        : dude
  Hash Name   : dude00ca7a20e93541a0a9cc930fb97bfd6b
  Ip/Hostname : huey-vbox
  Firewall    : true
  Alive       : True
  Connection  : wired
  Latency from Hub(ms)
    Min/Max        : 0.070-0.135
    Average        : 0.094
    Mean Deviation : 0.019
  Public Interface
          : /dude00ca7a20e93541a0a9cc930fb97bfd6b/invite-service-/app_manager
          : /dude00ca7a20e93541a0a9cc930fb97bfd6b/incompatible_app_list-publisher-/app_manager
          : /dude00ca7a20e93541a0a9cc930fb97bfd6b/app_list-publisher-/app_manager
          : /dude00ca7a20e93541a0a9cc930fb97bfd6b/list_apps-service-/app_manager
          : /dude00ca7a20e93541a0a9cc930fb97bfd6b/platform_info-service-/app_manager
          : /dude00ca7a20e93541a0a9cc930fb97bfd6b/status-service-/app_manager
  Flipped Interface
          : -
  Pulled Interface
          : -
```

**Comment by stonier** [comment]
Timeout fixed in https://github.com/robotics-in-concert/rocon_concert/pull/182

**Comment by stonier** [comment]
Huey, is the second problem still valid?

**Comment by hughie** [comment]
I did update and recompile and there is another error. I think it is not commit yet.

```
ROS_MASTER_URI=http://huey-VBox:11311/
setting /run_id to 12d4f49e-9245-11e3-b540-080027c3c5a4
process[rosout-1]: started with pid [6379]
started core service [/rosout]
process[concert/master-2]: started with pid [6406]
process[concert/services-3]: started with pid [6419]
process[concert/conductor-4]: started with pid [6435]
process[concert/scheduler-5]: started with pid [6484]
ERROR: cannot launch node of type [rocon_interactions/rocon_interactions_manager.py]: rocon_interactions
ROS path [0]=/opt/ros/hydro/share/ros
ROS path [1]=/home/huey/rocon/src
ROS path [2]=/opt/ros/hydro/share
ROS path [3]=/opt/ros/hydro/stacks
Traceback (most recent call last):
  File "/home/huey/rocon/src/rocon_concert/concert_service_manager/scripts/service_manager", line 19, in <module>
    sm = ServiceManager()
  File "/home/huey/rocon/src/rocon_concert/concert_service_manager/src/concert_service_manager/service_manager.py", line 34, in __init__
    self._role_app_loader = rocon_interactions.RoleAppLoader()
AttributeError: 'module' object has no attribute 'RoleAppLoader'
[concert/services-3] process has died [pid 6419, exit code 1, cmd /home/huey/rocon/src/rocon_concert/concert_service_manager/scripts/service_manager __name:=services __log:=/home/huey/.ros/log/12d4f49e-9245-11e3-b540-080027c3c5a4/concert-services-3.log].
log file: /home/huey/.ros/log/12d4f49e-9245-11e3-b540-080027c3c5a4/concert-services-3*.log
process[concert/hub-7]: started with pid [6553]
[INFO] [WallTime: 1392031131.301515] scheduler request topic: /concert/scheduler/requests
process[concert/gateway-8]: started with pid [6645]
process[concert/zeroconf/zeroconf-9]: started with pid [6741]
[INFO] [WallTime: 1392031135.505492] Hub : reset hub variables on the redis server.
[INFO] [WallTime: 1392031135.800615] Hub : advertising 'Concert Tutorial' on zeroconf [_ros-multimaster-hub._tcp, port 6380]
[ INFO] [1392031135.874513906]: Zeroconf: service successfully established [Concert Tutorial][_concert-master._tcp][11311]
Established under name 'Concert Tutorial'
```

**Comment by stonier** [comment]
Should be all there now.

**Comment by stonier** [comment]
Closing this as it's been idle for a while. Reopen if this is still an issue.
