### ISSUE TITLE
AttributeError: type object 'Strings' has no attribute 'SCHEDULER_REQUESTS' in teleop concert

### ISSUE THREAD

**Issue by jihoonl** [robotics-in-concert/rocon_tutorials#35]
```
[INFO] [WallTime: 1396226159.985878] Service Manager: service enabled [teleop] [teleop]
Traceback (most recent call last):
  File "/home/jihoonl/research/ros/rocon/src/rocon_services/rocon_service_teleop/scripts/teleop_pimp.py", line 200, in <module>
    pimp = TeleopPimp()
  File "/home/jihoonl/research/ros/rocon/src/rocon_services/rocon_service_teleop/scripts/teleop_pimp.py", line 76, in __init__
    self.requester = self.setup_requester(self.service_id)
  File "/home/jihoonl/research/ros/rocon/src/rocon_services/rocon_service_teleop/scripts/teleop_pimp.py", line 85, in setup_requester
    topic = concert_msgs.Strings.SCHEDULER_REQUESTS
AttributeError: type object 'Strings' has no attribute 'SCHEDULER_REQUESTS'
```

**Comment by stonier** [comment]
Sorry, missed a sync back to hydro-devel from indigo.

Do a git pull on your rocon_services.

**Comment by jihoonl** [comment]
rocon_msgs in unsynced as well. please merge it too.

**Comment by jihoonl** [comment]
```
Traceback (most recent call last):
  File "/home/jihoonl/research/ros/rocon/src/rocon_services/rocon_service_turtlesim/scripts/hatchling.py", line 150, in <module>
    hatchling = Hatchling()
  File "/home/jihoonl/research/ros/rocon/src/rocon_services/rocon_service_turtlesim/scripts/hatchling.py", line 55, in __init__
    self.spawn_turtle = rocon_python_comms.ServicePairClient('spawn', rocon_service_msgs.SpawnTurtlePair)
AttributeError: 'module' object has no attribute 'SpawnTurtlePair'
```

**Comment by jihoonl** [comment]
```
Established under name 'Turtle Teleop Concert'
Traceback (most recent call last):
  File "/home/jihoonl/research/ros/rocon/src/rocon_services/rocon_service_turtlesim/scripts/turtle_herder.py", line 182, in <module>
    turtle_herder = TurtleHerder()
  File "/home/jihoonl/research/ros/rocon/src/rocon_services/rocon_service_turtlesim/scripts/turtle_herder.py", line 75, in __init__
    self._kill_turtle_service_pair_server = rocon_python_comms.ServicePairServer('kill', self._kill_turtle_service, rocon_service_msgs.KillTurtlePair, use_threads=True)
AttributeError: 'module' object has no attribute 'KillTurtlePair'
```

**Comment by jihoonl** [comment]
Still it causes errors.

**Comment by stonier** [comment]
Ach...it wasn't unsynced. Was a problem created by fixing the problem. Pull rocon_msgs again.

**Comment by stonier** [comment]
Thanks for catching this.

**Comment by stonier** [comment]
Updated rocon_msgs...again. Let me know if it is still broken. Sorry!

**Comment by jihoonl** [comment]
Works good now! :100:
