### ISSUE TITLE
chatter concert is failing

### ISSUE THREAD

**Issue by stonier** [robotics-in-concert/rocon_tutorials#59]
```
Traceback (most recent call last):
  File "/opt/rocon/src/rocon_concert/concert_service_manager/scripts/service_manager", line 22, in <module>
    sm = ServiceManager()
  File "/opt/rocon/src/rocon_concert/concert_service_manager/src/concert_service_manager/service_manager.py", line 66, in __init__
    self._eable_default_service()
  File "/opt/rocon/src/rocon_concert/concert_service_manager/src/concert_service_manager/service_manager.py", line 92, in _eable_default_service
    self._ros_service_enable_concert_service(concert_srvs.EnableServiceRequest(name, True))
  File "/opt/rocon/src/rocon_concert/concert_service_manager/src/concert_service_manager/service_manager.py", line 174, in _ros_service_enable_concert_service
    self._service_pool.reload_services()
  File "/opt/rocon/src/rocon_concert/concert_service_manager/src/concert_service_manager/service_pool.py", line 314, in reload_services
    if self._check_solution_config_modification():
  File "/opt/rocon/src/rocon_concert/concert_service_manager/src/concert_service_manager/service_pool.py", line 239, in _check_solution_config_modification
    if not rocon_python_utils.ros.is_validation_file(self._solution_config_file):
AttributeError: 'module' object has no attribute 'is_validation_file'
```

**Comment by dwlee** [comment]
May you update rocon_tools? I also update rocon tools.

https://github.com/robotics-in-concert/rocon_tools/pull/77/files

**Comment by stonier** [comment]
Ach, 1am bug hunting...yes, that solves that problem. Getting other issues though:

1) Not important, but strange warning on the concert: ~~https://github.com/robotics-in-concert/rocon_concert/issues/275~~

```
Warning: fuschia is not a known color.
```

2) Also not important, but a debug print that should be cleaned out

```
Searching for the conductor's ros topics...
```

3) VERY IMPORTANT : not always, but often failing to start - clients are looping continually with:

Concert:

```
[INFO] [WallTime: 1426556552.805717] Conductor : no hub yet available, spinning...
[INFO] [WallTime: 1426556552.805904] Conductor : no hub yet available, spinning...
[INFO] [WallTime: 1426556552.806029] Gateway : Found existing mismatched public key on the hub. Requesting resend for all flip-ins.
[INFO] [WallTime: 1426556552.806095] Conductor : no hub yet available, spinning...
[INFO] [WallTime: 1426556552.806298] Conductor : no hub yet available, spinning...
[INFO] [WallTime: 1426556552.806554] Conductor : no hub yet available, spinning...
[INFO] [WallTime: 1426556552.806594] Gateway : registering on the hub [Chatter Concert]
[INFO] [WallTime: 1426556552.806756] Conductor : no hub yet available, spinning...
[INFO] [WallTime: 1426556552.806920] Conductor : no hub yet available, spinning...
[INFO] [WallTime: 1426556552.807030] Conductor : no hub yet available, spinning...
[INFO] [WallTime: 1426556552.807132] Conductor : no hub yet available, spinning...
[INFO] [WallTime: 1426556552.807233] Conductor : no hub yet available, spinning...
```

Clients:

```
[INFO] [WallTime: 1426556010.183869] Gateway : discovered hub directly [http://localhost:6380]
```

**Comment by stonier** [comment]
Moved 3) to #60.

**Comment by stonier** [comment]
1) cleaned up in https://github.com/robotics-in-concert/rocon_concert/commit/304c50d5073390efe7b0857c201f3ea80a6399fb

**Comment by stonier** [comment]
Other frequently occurring termination issues with hanging symptoms:

1) A rocon_launch terminal id?:

```
Invalid pid value [None][an integer is required]
```

2) Clients hanging when they can't contact the server (I missed the ouput here).

**Comment by stonier** [comment]
Closing here, moved termination issues to #61.
